[package]
name = "resistance-cmacm"
version = "0.1.0"
edition = "2021"

[dependencies]
resistance-civil-protection = { path = "../resistance-civil-protection/" }
clap = { version = "4.5.26", features = ["derive"] }
rpassword = "7.3.1"
syslog = "7.0.0"
log = "0.4.25"

